name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run linter (flake8)
        run: flake8 .

      - name: Run unit tests
        run: PYTHONPATH=. pytest tests

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.actor }}/my-app:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.actor }}/my-app:latest

      - name: Notify Slack (on success)
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ CI прошёл успешно для ${{ github.repository }} в ветке `${{ github.ref_name }}`."}' \
          ${{ secrets.SLACK_WEBHOOK }}

      - name: Notify Slack (on failure)
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"❌ CI упал для ${{ github.repository }} в ветке `${{ github.ref_name }}`."}' \
          ${{ secrets.SLACK_WEBHOOK }}
